# Generated by Django 5.2.11 on 2026-02-14 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='account.userrole'),
            preserve_default=False,
        ),
    ]
