# Generated by Django 5.2.11 on 2026-02-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no src', upload_to=''),
            preserve_default=False,
        ),
    ]
