# Generated by Django 5.2.11 on 2026-02-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_product_created_date_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verfired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
