# Generated by Django 5.2.11 on 2026-02-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_is_verfired_user_verify_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verfired',
            new_name='is_verified',
        ),
    ]
